Add zh-TW translations
golang-standards/project-layout pull request #84
Opened 2020-10-31 17:16 UTC by doggy8088

https://github.com/golang-standards/project-layout/issues/83

2020-10-31 18:41 UTC, YamiOdymel approved these changes

2020-10-31 18:42 UTC, LittlePaulHi approved these changes

2020-11-01 02:03 UTC, ydFu approved these changes

2020-11-01 03:49 UTC, appleboy commented on README_zh-TW.md
> +如果你才剛開始學習 Go 程式語言，或者你只是想建立一個實驗性的玩具專案，這個專案目錄結構就過於複雜了。從一個非常簡單的 `main.go` 檔案開始，其實已經綽綽有餘。但隨著專案增長，你一定要記得，維持一份良好的程式碼結構其實是非常重要的，否則你最終將會得到一堆淩亂的程式碼，這其中肯定也會包含大量隱藏的相依問題與全域狀態。當有越多人參與專案時，你也將需要更多、更好的目錄結構。這時候就是帶入套件
**私有的** 前面不需要空白

2020-11-01 03:50 UTC, appleboy commented on README_zh-TW.md
> +當專案的根目錄包含許多不是用 Go 所寫的元件與目錄時，將 Go 程式碼放在一個集中的目錄下也是種不錯的方法，這使得運行各種 Go 工具變得更加容易（正如以下這些演講中提到的那樣：來自 GopherCon EU 2018 的 [`Best Practices for Industrial Programming`](https://www.youtube.com/watch?v=PTE4VJId
最後多一個 `)` ?

2020-11-01 03:50 UTC, appleboy commented on README_zh-TW.md
> +注意：從 [`Go 1.13`](https://golang.org/doc/go1.13#modules) 開始，Go 預設啟用了**模組的代理伺服器**(module proxy)功能 (預設使用 [`https://proxy.golang.org`](https://proxy.golang.org) 作為模組的代理伺服器)。你可以從[`這裡`](https://blog.golang
(module proxy) 前後補上一個空白

2020-11-01 03:51 UTC, appleboy commented on README_zh-TW.md
> +將你的 CI (travis, circle, drone) 的組態設定與腳本放在 `/build/ci` 目錄中。請注意：有些 CI 工具(例如 Travis CI 等)，它們對這些組態設定檔案的位置非常挑剔。如果可能的話，請嘗試將檔案放在 `/build/ci` 目錄中，並**連結**(linking)這些檔案到 CI 工具期望它們出現的位置。
`(內容)` 格式前後都需要空白，除非遇到標點符號。

2020-11-01 03:52 UTC, appleboy commented on README_zh-TW.md
> +請查看  [`/test`](test/README.md) 目錄獲得更多範例。
`請查看` 後面多一個空白

2020-11-01 03:53 UTC, appleboy requested changes
一些編排上的修正，再麻煩看看。可能有些沒檢查出來

2020-11-01 03:58 UTC, Tony-Liou approved these changes

2020-11-01 05:32 UTC, doggy8088 commented on README_zh-TW.md
> +當專案的根目錄包含許多不是用 Go 所寫的元件與目錄時，將 Go 程式碼放在一個集中的目錄下也是種不錯的方法，這使得運行各種 Go 工具變得更加容易（正如以下這些演講中提到的那樣：來自 GopherCon EU 2018 的 [`Best Practices for Industrial Programming`](https://www.youtube.com/watch?v=PTE4VJId
並沒有
![image](https://user-images.githubusercontent.com/88981/97795880-a9621d00-1c46-11eb-8e33-675486d8c567.png)

2020-11-01 05:34 UTC, ray247k approved these changes

2020-11-01 05:34 UTC, doggy8088 commented on README_zh-TW.md
> +將你的 CI (travis, circle, drone) 的組態設定與腳本放在 `/build/ci` 目錄中。請注意：有些 CI 工具(例如 Travis CI 等)，它們對這些組態設定檔案的位置非常挑剔。如果可能的話，請嘗試將檔案放在 `/build/ci` 目錄中，並**連結**(linking)這些檔案到 CI 工具期望它們出現的位置。
Okay

2020-11-01 05:35 UTC, doggy8088 commented on README_zh-TW.md
> +如果你才剛開始學習 Go 程式語言，或者你只是想建立一個實驗性的玩具專案，這個專案目錄結構就過於複雜了。從一個非常簡單的 `main.go` 檔案開始，其實已經綽綽有餘。但隨著專案增長，你一定要記得，維持一份良好的程式碼結構其實是非常重要的，否則你最終將會得到一堆淩亂的程式碼，這其中肯定也會包含大量隱藏的相依問題與全域狀態。當有越多人參與專案時，你也將需要更多、更好的目錄結構。這時候就是帶入套件
改好了！

2020-11-01 05:36 UTC, doggy8088 commented on README_zh-TW.md
> +注意：從 [`Go 1.13`](https://golang.org/doc/go1.13#modules) 開始，Go 預設啟用了**模組的代理伺服器**(module proxy)功能 (預設使用 [`https://proxy.golang.org`](https://proxy.golang.org) 作為模組的代理伺服器)。你可以從[`這裡`](https://blog.golang
改好了！

2020-11-01 05:36 UTC, doggy8088 commented on README_zh-TW.md
> +將你的 CI (travis, circle, drone) 的組態設定與腳本放在 `/build/ci` 目錄中。請注意：有些 CI 工具(例如 Travis CI 等)，它們對這些組態設定檔案的位置非常挑剔。如果可能的話，請嘗試將檔案放在 `/build/ci` 目錄中，並**連結**(linking)這些檔案到 CI 工具期望它們出現的位置。
都改好了！

2020-11-01 05:36 UTC, doggy8088 commented on README_zh-TW.md
> +請查看  [`/test`](test/README.md) 目錄獲得更多範例。
改好了！

2020-11-01 06:47 UTC, ydFu commented on README_zh-TW.md
> +將你的 CI (travis, circle, drone) 的組態設定與腳本放在 `/build/ci` 目錄中。請注意：有些 CI 工具 (例如 Travis CI 等)，它們對這些組態設定檔案的位置非常挑剔。如果可能的話，請嘗試將檔案放在 `/build/ci` 目錄中，並**連結** (linking) 這些檔案到 CI 工具期望它們出現的位置。
* 原始文案為:
...(例如 Travis CI 等)...

* 提議調整文案
...(例如 : Travis CI 等)...

2020-11-01 06:50 UTC, ydFu commented on README_zh-TW.md
> +其他要一併放入儲存庫的相關檔案 (例如圖片、LOGO、... 等等)。
原始文案 :
... (例如圖片、LOGO、... 等等)。

建議調整文案 :
...(例如： 圖片、LOGO、... 等等)。

2020-11-01 17:35 UTC, doggy8088 commented on README_zh-TW.md
> +將你的 CI (travis, circle, drone) 的組態設定與腳本放在 `/build/ci` 目錄中。請注意：有些 CI 工具 (例如 Travis CI 等)，它們對這些組態設定檔案的位置非常挑剔。如果可能的話，請嘗試將檔案放在 `/build/ci` 目錄中，並**連結** (linking) 這些檔案到 CI 工具期望它們出現的位置。
改好了，謝謝

2020-11-01 17:35 UTC, doggy8088 commented on README_zh-TW.md
> +其他要一併放入儲存庫的相關檔案 (例如圖片、LOGO、... 等等)。
改好了，謝謝

2020-11-02 04:29 UTC, appleboy requested changes

2020-11-02 04:29 UTC, appleboy commented on README_zh-TW.md
> +
這邊的 badge 格式要等 https://github.com/golang-standards/project-layout/pull/85 再修正吧？

2020-11-02 04:51 UTC, doggy8088 commented on README_zh-TW.md
> +
哈哈，我先改了，沒差吧？ XD

2020-11-02 04:52 UTC, doggy8088 commented on README_zh-TW.md
> +
他原本的格是我一開始還真的完全看不懂他在寫些什麼，後來才發現他把 Badge 全部放在下面！

2020-11-02 13:37 UTC, appleboy commented on README_zh-TW.md
> +
我的建議是除非官方的 Readme 格式已經修正為 #85，這樣你就可以在這文件上做修正，不然還是用回原本的格式比較好。

2020-11-02 14:20 UTC, appleboy approved these changes

2021-01-29 19:34 UTC, merged