Add Japanese translation
golang-standards/project-layout pull request #88
Opened 2020-12-10 15:15 UTC by kamiyagunji

2020-12-10 15:33 UTC, yoshikawa requested changes
LGTM!!
2点ほど気になったので変更および、理由を聞けると嬉しいです！
本当にお疲れさまでしたmm

2020-12-10 15:33 UTC, yoshikawa commented on README_ja.md
> +Goを学ぼうとしている場合や、自分でPoCやおもちゃのプロジェクトを構築しようとしている場合、このプロジェクトレイアウトはやりすぎです。最初は本当にシンプルなものから始めてください（`main.go`ファイルが1つあれば十分です）。プロジェクトが大きくなってくると、コードがきちんと構造化されているかどうかが重要になってくることを覚えておいてください。そうしないと、多くの隠れた依存関係やグローバル
`プロジェクトが大きくなってくると、コードがきちんと構造化されているかどうかが重要になってくることを覚えておいてください。`
プロジェクトが大きくなるにつれて、コードが適切に構造化されているかどうかが重要になることに注意してください。

2020-12-10 15:33 UTC, yoshikawa commented on README_ja.md
> +例に関しては、[`/ cmd`](cmd/README.md)ディレクトリを参照してください。
`/cmd` 　でないのが気になりました

2020-12-10 15:34 UTC, yoshikawa commented on README_ja.md
> +Goを学ぼうとしている場合や、自分でPoCやおもちゃのプロジェクトを構築しようとしている場合、このプロジェクトレイアウトはやりすぎです。最初は本当にシンプルなものから始めてください（`main.go`ファイルが1つあれば十分です）。プロジェクトが大きくなってくると、コードがきちんと構造化されているかどうかが重要になってくることを覚えておいてください。そうしないと、多くの隠れた依存関係やグローバル
大体、一緒なので大丈夫そうですね

2020-12-10 15:36 UTC, kamiyagunji commented on README_ja.md
> +例に関しては、[`/ cmd`](cmd/README.md)ディレクトリを参照してください。
これはミスですね。。

3087cf6

2020-12-10 15:39 UTC, kamiyagunji commented on README_ja.md
> +Goを学ぼうとしている場合や、自分でPoCやおもちゃのプロジェクトを構築しようとしている場合、このプロジェクトレイアウトはやりすぎです。最初は本当にシンプルなものから始めてください（`main.go`ファイルが1つあれば十分です）。プロジェクトが大きくなってくると、コードがきちんと構造化されているかどうかが重要になってくることを覚えておいてください。そうしないと、多くの隠れた依存関係やグローバル
ちょっとイントネーション的に変ですね。

挙げていただいたものに変更します！

2020-12-10 16:04 UTC, yoshikawa approved these changes
LGTM!!🎉🎉

2020-12-19 07:31 UTC, kamiyagunji commented
@kcq 
Can you merge after checking?

2021-01-29 18:02 UTC, merged

2021-01-29 18:09 UTC, kcq commented
Merged